context:
  version: "0.6.0"

package:
  name: sqlfluff-lsp
  version: ${{ version }}

source:
  url: https://github.com/VasanthakumarV/sqlfluff-lsp/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b34df07b177c27dfea9fc6a7e36188ec81187610654c6c49107dc263a02be3cc

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then: |
          cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
          cargo auditable install --locked --no-track --path . --root ${PREFIX}
        else: |
          cargo-bundle-licenses --format yaml --output %SRC_DIR%\THIRDPARTY.yml
          cargo auditable install --locked --no-track --path . --root %LIBRARY_PREFIX%

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
  run:
    - sqlfluff >=3,<5

tests:
  - script:
      - sqlfluff-lsp --version

about:
  homepage: https://github.com/VasanthakumarV/sqlfluff-lsp
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  description: "Language Server for the SQL linting & formatting tool, SQLFluff."
  summary: "Language Server for the SQL linting & formatting tool, SQLFluff."

extra:
  recipe-maintainers:
    - VasanthakumarV
